--------------------------------
-- Civilizations
--------------------------------		
INSERT INTO Civilizations
			(Type, 									Description, 								ShortDescription, 								Adjective, 										Civilopedia, CivilopediaTag, DefaultPlayerColor, 				 ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, 																										IconAtlas, 	PortraitIndex, 	AlphaIconAtlas,		MapImage, 						DawnOfManQuote, 						DawnOfManImage, DawnOfManAudio)
SELECT		('CIVILIZATION_WWII_UK'), 	('TXT_KEY_CIV_WWII_UNITED_KINGDOM_DESC'), 	('TXT_KEY_CIV_WWII_UNITED_KINGDOM_SHORT_DESC'), 	('TXT_KEY_CIV_WWII_UNITED_KINGDOM_ADJECTIVE'),	Civilopedia, CivilopediaTag, DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, ('WW2_FLAGS'), 	1, ('WW2_FLAGS'), 	('mapUnitedKingdom.dds'), 	('TXT_KEY_WWII_CHURCHILL_DAWN'), 	('dom_uk.dds'), ('AS2D_DOM_SPEECH_ENGLAND') FROM Civilizations WHERE (Type = 'CIVILIZATION_ENGLAND') UNION ALL
SELECT		('CIVILIZATION_WWII_FRANCE'), 	('TXT_KEY_CIV_WWII_FRANCE_DESC'), 	('TXT_KEY_CIV_WWII_FRANCE_SHORT_DESC'), 	('TXT_KEY_CIV_WWII_FRANCE_ADJECTIVE'),	Civilopedia, CivilopediaTag, DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, ('WW2_FLAGS'), 	5, ('WW2_FLAGS'), 	('mapFrance.dds'), 	('TXT_KEY_WWII_DEGAULLE_DAWN'), 	('dom_france.dds'), ('AS2D_DOM_SPEECH_FRANCE') FROM Civilizations WHERE (Type = 'CIVILIZATION_FRANCE') UNION ALL
SELECT		('CIVILIZATION_WWII_GERMANY'), 	('TXT_KEY_CIV_WWII_GERMANY_DESC'), 	('TXT_KEY_CIV_WWII_GERMANY_SHORT_DESC'), 	('TXT_KEY_CIV_WWII_GERMANY_ADJECTIVE'),	Civilopedia, CivilopediaTag, DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, ('WW2_FLAGS'), 	0, ('WW2_FLAGS'), 	('mapGermany.dds'), 	('TXT_KEY_WWII_HITLER_DAWN'), 	('dom_germany.dds'), ('AS2D_DOM_SPEECH_GERMANY') FROM Civilizations WHERE (Type = 'CIVILIZATION_GERMANY') UNION ALL
SELECT		('CIVILIZATION_WWII_ITALY'), 	('TXT_KEY_CIV_WWII_ITALY_DESC'), 	('TXT_KEY_CIV_WWII_ITALY_DESC'), 	('TXT_KEY_CIV_WWII_ITALY_ADJECTIVE'),	Civilopedia, CivilopediaTag, DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, ('WW2_FLAGS'), 	6, ('WW2_FLAGS'), 	('mapItaly.dds'), 	('TXT_KEY_WWII_MUSSOLINI_DAWN'), 	('dom_italy.dds'), ('AS2D_DOM_SPEECH_ITALY') FROM Civilizations WHERE (Type = 'CIVILIZATION_ROME');

--------------------------------	
-- Civilization_Leaders
--------------------------------	
INSERT INTO Civilization_Leaders
	(CivilizationType, 						LeaderheadType)
VALUES		
	('CIVILIZATION_WWII_UK',		'LEADER_WWII_CHURCHILL'),
	('CIVILIZATION_WWII_FRANCE',		'LEADER_WWII_DEGAULLE'),
	('CIVILIZATION_WWII_GERMANY',		'LEADER_WWII_HITLER'),
	('CIVILIZATION_WWII_ITALY',		'LEADER_WWII_MUSSOLINI');

/*
UPDATE PlayerColors SET PrimaryColor = 'COLOR_PLAYER_WHITE' WHERE Type = 'PLAYERCOLOR_FRANCE';
UPDATE PlayerColors SET PrimaryColor = 'COLOR_PLAYER_WHITE' WHERE Type = 'PLAYERCOLOR_GERMANY';
UPDATE PlayerColors SET PrimaryColor = 'COLOR_PLAYER_WHITE', SecondaryColor = 'COLOR_PLAYER_DARK_DARK_GREEN' WHERE Type = 'PLAYERCOLOR_ROME';
UPDATE PlayerColors SET PrimaryColor = 'COLOR_PLAYER_WHITE', SecondaryColor = 'COLOR_PLAYER_RED' WHERE Type = 'PLAYERCOLOR_RUSSIA';
UPDATE PlayerColors SET PrimaryColor = 'COLOR_PLAYER_WHITE', SecondaryColor = 'COLOR_PLAYER_DARK_DARK_GREEN' WHERE Type = 'PLAYERCOLOR_ROME';
UPDATE PlayerColors SET SecondaryColor = 'COLOR_PLAYER_DARK_BLUE' WHERE Type = 'PLAYERCOLOR_ENGLAND';
*/
/*
INSERT INTO Civilizations VALUES(2,'CIVILIZATION_ENGLAND',		'TXT_KEY_CIV_ENGLAND_DESC',		NULL,'TXT_KEY_CIV5_ENGLAND',			NULL,1,1,'TXT_KEY_CIV_ENGLAND_SHORT_DESC',		'TXT_KEY_CIV_ENGLAND_ADJECTIVE',	'PLAYERCOLOR_ENGLAND',		'ART_DEF_CIVILIZATION_ENGLAND',		'ARTSTYLE_EUROPEAN',		'_EURO',		'EUROPEAN',		NULL,1,	'WW2_FLAGS',			'WW2_FLAGS',		'MapEngland512.dds',		'TXT_KEY_CIV5_DAWN_ENGLAND_TEXT',		'DOM_Elizabeth.dds',	'AS2D_DOM_SPEECH_ENGLAND',		NULL,NULL);
INSERT INTO Civilizations VALUES(0,'CIVILIZATION_AMERICA',		'TXT_KEY_CIV_AMERICA_DESC',		NULL,'TXT_KEY_CIV5_UNITEDSTATES',		NULL,1,1,'TXT_KEY_CIV_AMERICA_SHORT_DESC',		'TXT_KEY_CIV_AMERICA_ADJECTIVE',	'PLAYERCOLOR_AMERICA',		'ART_DEF_CIVILIZATION_AMERICA',		'ARTSTYLE_EUROPEAN',		'_EURO',		'EUROPEAN',		NULL,3,	'WW2_FLAGS',			'WW2_FLAGS',		'MapAmerica512.dds',		'TXT_KEY_CIV5_DAWN_UNITEDSTATES_TEXT',	'DOM_Washington.dds',	'AS2D_DOM_SPEECH_UNITED_STATES',NULL,NULL);
INSERT INTO Civilizations VALUES(1,'CIVILIZATION_CHINA',		'TXT_KEY_CIV_CHINA_DESC',		NULL,'TXT_KEY_CIV5_CHINA',				NULL,1,1,'TXT_KEY_CIV_CHINA_SHORT_DESC',		'TXT_KEY_CIV_CHINA_ADJECTIVE',		'PLAYERCOLOR_CHINA',		'ART_DEF_CIVILIZATION_CHINA',		'ARTSTYLE_ASIAN',			'_ASIA',		'ASIAN',		NULL,7,	'WW2_FLAGS',			'WW2_FLAGS',		'Earth1936startscreen.dds',	'TXT_KEY_CIV5_DAWN_CHINA_TEXT',			'DOM_Wu.dds',			'AS2D_DOM_SPEECH_CHINA',		NULL,NULL);
INSERT INTO Civilizations VALUES(3,'CIVILIZATION_FRANCE',		'TXT_KEY_CIV_FRANCE_DESC',		NULL,'TXT_KEY_CIV5_FRANCE',				NULL,1,1,'TXT_KEY_CIV_FRANCE_SHORT_DESC',		'TXT_KEY_CIV_FRANCE_ADJECTIVE',		'PLAYERCOLOR_FRANCE',		'ART_DEF_CIVILIZATION_FRANCE',		'ARTSTYLE_EUROPEAN',		'_EURO',		'EUROPEAN',		NULL,5,	'WW2_FLAGS',			'WW2_FLAGS',		'Earth1936startscreen.dds',	'TXT_KEY_CIV5_DAWN_FRANCE_TEXT',		'DOM_Napoleon.dds',		'AS2D_DOM_SPEECH_FRANCE',		NULL,NULL);
INSERT INTO Civilizations VALUES(4,'CIVILIZATION_GERMANY',		'TXT_KEY_CIV_GERMANY_DESC',		NULL,'TXT_KEY_CIV5_GERMANY',			NULL,1,1,'TXT_KEY_CIV_GERMANY_SHORT_DESC',		'TXT_KEY_CIV_GERMANY_ADJECTIVE',	'PLAYERCOLOR_GERMANY',		'ART_DEF_CIVILIZATION_GERMANY',		'ARTSTYLE_EUROPEAN',		'_EURO',		'EUROPEAN',		NULL,0,	'WW2_FLAGS',			'WW2_FLAGS',		'MapGermany512.dds',		'TXT_KEY_CIV5_DAWN_GERMANY_TEXT',		'DOM_Bizmark.dds',		'AS2D_DOM_SPEECH_GERMANY',		NULL,NULL);
INSERT INTO Civilizations VALUES(5,'CIVILIZATION_GREECE',		'TXT_KEY_RED_WWII_GREECE',		NULL,'TXT_KEY_WW2_SCENARIO_CIV_GREECE',	NULL,1,1,'TXT_KEY_RED_WWII_GREECE_SHORT',		'TXT_KEY_CIV_GREECE_ADJECTIVE',		'PLAYERCOLOR_GREECE',		'ART_DEF_CIVILIZATION_GREECE',		'ARTSTYLE_GRECO_ROMAN',		'_MED',			'MEDITERRANEAN',NULL,17,'WW2_FLAGS',			'WW2_FLAGS',		'Earth1936startscreen.dds',	'TXT_KEY_RED_EURO1940_GREECE_BRIEFING',	'dom_greece.dds',		'AS2D_DOM_SPEECH_GREECE',		NULL,NULL);
INSERT INTO Civilizations VALUES(6,'CIVILIZATION_JAPAN',		'TXT_KEY_CIV_JAPAN_DESC',		NULL,'TXT_KEY_CIV5_JAPAN',				NULL,1,1,'TXT_KEY_CIV_JAPAN_SHORT_DESC',		'TXT_KEY_CIV_JAPAN_ADJECTIVE',		'PLAYERCOLOR_JAPAN',		'ART_DEF_CIVILIZATION_JAPAN',		'ARTSTYLE_ASIAN',			'_ASIA',		'ASIAN',		NULL,4, 'WW2_FLAGS',			'WW2_FLAGS',		'MapJapan512.dds',			'TXT_KEY_CIV5_DAWN_JAPAN_TEXT',			'DOM_Oda.dds',			'AS2D_DOM_SPEECH_JAPAN',		NULL,NULL);
INSERT INTO Civilizations VALUES(7,'CIVILIZATION_ROME',			'TXT_KEY_CIV_ROME_DESC',		NULL,'TXT_KEY_CIV5_ROME',				NULL,1,1,'TXT_KEY_CIV_ROME_SHORT_DESC',			'TXT_KEY_CIV_ROME_ADJECTIVE',		'PLAYERCOLOR_ROME',			'ART_DEF_CIVILIZATION_ROME',		'ARTSTYLE_GRECO_ROMAN',		'_MED',			'MEDITERRANEAN',NULL,6, 'WW2_FLAGS',			'WW2_FLAGS',		'MapRome512.dds',			'TXT_KEY_CIV5_DAWN_ROME_TEXT',			'DOM_Augustus.dds',		'AS2D_DOM_SPEECH_ROME',			NULL,NULL);
INSERT INTO Civilizations VALUES(8,'CIVILIZATION_RUSSIA',		'TXT_KEY_CIV_RUSSIA_DESC',		NULL,'TXT_KEY_CIV5_RUSSIA',				NULL,1,1,'TXT_KEY_CIV_RUSSIA_SHORT_DESC',		'TXT_KEY_CIV_RUSSIA_ADJECTIVE',		'PLAYERCOLOR_RUSSIA',		'ART_DEF_CIVILIZATION_RUSSIA',		'ARTSTYLE_EUROPEAN',		'_EURO',		'EUROPEAN',		NULL,2, 'WW2_FLAGS',			'WW2_FLAGS',		'MapRussia512.dds',			'TXT_KEY_CIV5_DAWN_RUSSIA_TEXT',		'DOM_Catherine.dds',	'AS2D_DOM_SPEECH_RUSSIA',		NULL,NULL);
*/